version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  feature:
    build: .
    environment:
      PORT: 8000
      MONGO_URI: mongodb://mongo
      MONGO_USER_COLLECTION_NAME: users
    ports:
      - 8000:8000
