version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  redis:
    image: redis
    ports:
      - 6379:6379

  users:
    build: .
    environment:
      PORT: 8000
      MONGO_URI: mongodb://mongo
      MONGO_USER_COLLECTION_NAME: users
    # volumes:
    #   - asset-volume:/usr/src/app
    ports:
      - 8000:8000

  # incoming-proxy-service:
  #   image: registry.gitlab.com/yesodot/rnd/terminal-rabaz/shared/spike-proxy-service
  #   volumes:
  #     - asset-volume:/usr/src/app
  #   environment:
  #     MODE: incoming
  #     PORT: 8000
  #     MONGO_URI: mongodb://mongo
  #     MONGO_USER_COLLECTION_NAME: users
  #     SPIKE_PUBLIC_KEY_FULL_PATH: '/usr/src/app/publickey.pem'
  #     INCOMING_SERVICES: >
  #       [
  #         {
  #           "target": "http://users:8000",
  #           "audience": "aLFUQ447znCQqVZb4daIjv9NM7CyPx",
  #           "secure": false,
  #           "useBearerToken": false,
  #           "routes": [
  #             {
  #               "route": "/api/users",
  #               "method": "get",
  #               "allowedScopes": [
  #                 "read"
  #               ]
  #             },
  #             {
  #               "route": "/api/users",
  #               "method": "post",
  #               "allowedScopes": [
  #                 "create"
  #               ]
  #             },
  #             {
  #               "route": "/api/users",
  #               "method": "delete",
  #               "allowedScopes": [
  #                 "delete"
  #               ]
  #             }
  #           ]
  #         }
  #       ]
  #   ports:
  #     - 8001:8000
# 
# volumes:
#   asset-volume:
